### ISSUE TITLE
Wrong File extension names

### ISSUE THREAD

**Issue by l4tt** [Brutal32/ShopBotnet.com-SRC#1]
Looking at the name convention on the files / extensions, I noticed that they are following the wrong file formats. Example main.php isn't php it's python. And file.txt is bash / powershell invokes. Also, I noticed from looking around the Python code that it encrypts files in the system, I guess, for a ransom malware attack. Anyways, the code looks clean from a Python point a view just looks like a beginner made it or chat gpt guidance. Whatever the case, maybe

**Comment by UniversalStorage** [comment]
umm

**Comment by Brutal32** [comment]
> Looking at the name convention on the files / extensions, I noticed that they are following the wrong file formats. Example main.php isn't php it's python. And file.txt is bash / powershell invokes. Also, I noticed from looking around the Python code that it encrypts files in the system, I guess, for a ransom malware attack. Anyways, the code looks clean from a Python point a view just looks like a beginner made it or chat gpt guidance. Whatever the case, maybe

Hi, idk why owner of "ShopBotnet.com" (yeah website dead and owner of website try leak my ip fr) use extension of file is php but code maybe its python, i think he ask chat gpt with stupid brain

**Comment by kaithub** [comment]
boohoo, you can't change a file ext to make a botnet using rune D:
